### ISSUE TITLE
Error: No module named 'common_constants'

### ISSUE THREAD

**Issue by kulmsc** [EBISPOT/sum-stats-formatter#49]
When running snakemake with the default Snakefile I received the following error: ModuleNotFoundError: No module named 'common_constants'

I cannot find any file name common_constants, or any package that can be downloaded by that name.  What exactly is common_constants and how can I get it?

**Comment by jdhayhurst** [comment]
Hi @kulmsc

I've split the harmonisation pipeline out into a separate repository: https://github.com/EBISPOT/gwas-sumstats-harmoniser
The harmonisation pipeline in this repository is being deprecated.

The code in the above mentioned repo has also been refactored so this issue you mentioned here should have been fixed.
