### ISSUE TITLE
Have option to reorder columns

### ISSUE THREAD

**Issue by jdhayhurst** [EBISPOT/sum-stats-formatter#82]
We need to be able to reorder the columns and automatically suggest the standard order

**Comment by earlEBI** [comment]
@jdhayhurst Hi James, I tried this using ss-format on a file in my folder called test2.tsv and test2.json but it didn't reorder - am I missing something? 
I did get this warning... might it be related? 
bash-4.4$ ss-format -f test2.tsv -m gen -c test2.json
.... PkgResourcesDeprecationWarning: 0.1-SNAPSHOT is an invalid version and will not be supported in a future release
  PkgResourcesDeprecationWarning,

**Comment by earlEBI** [comment]
@jdhayhurst Works great! Thanks!
